apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: inspec-demo-cluster
  region: us-east-2
  version: "1.22"

nodeGroups:
  - name: inspec-demo-ng-1
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
      allow: true