apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: vasundhara-nginx-app
  region: us-east-2

nodeGroups:
  - name: vasundhara-ng-1
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
      allow: true