apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspec-nginx-demo-app
spec:
  selector:
    matchLabels:
      run: inspec-nginx-demo-app
  replicas: 4
  template:
    metadata:
      labels:
        run: inspec-nginx-demo-app
    spec:
      containers:
      - name: inspec-nginx-demo-app
        image: nginx
        ports:
        - containerPort: 80
